version: '3.8'
services:
  nodeseeker:
    image: smhw3565/nodeseeker-docker:latest  
    container_name: nodeseeker-app
    restart: unless-stopped
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
      - HOST=0.0.0.0
      - DATABASE_PATH=/usr/src/app/data/nodeseeker.db
      - RSS_URL=${RSS_URL:-https://rss.nodeseek.com/}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3010}
    volumes:
      # 持久化数据库文件
      - nodeseeker_data:/usr/src/app/data
      # 日志目录
      - nodeseeker_logs:/usr/src/app/logs
    networks:
      - nodeseeker_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  nodeseeker_data:
    driver: local
  nodeseeker_logs:
    driver: local
networks:
  nodeseeker_network:
    driver: bridge